name: x_hub
description: "xHub"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  path: any
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  hive_flutter: ^1.1.0
  flutter_launcher_icons: ^0.13.1
  flutter_svg: ^2.0.5
  http: ^1.2.0
  path_provider: any
  provider: ^6.1.1
  easy_localization: ^3.0.1
  email_validator: ^2.1.16
  file_picker: ^6.1.1
  http_parser: ^4.0.2
  permission_handler: ^11.2.0
  flutter_file_downloader: ^1.2.1
  flutter_slidable: ^3.0.1
  webview_flutter: ^4.2.4
  device_info_plus: ^9.1.2
  get: ^4.6.6
  flutter_widget_from_html: ^0.14.11
  url_launcher: ^6.1.14
  flutter_verification_code: ^1.1.7
  flutter_local_notifications: ^11.0.0
  firebase_core: ^2.26.0
  firebase_messaging: ^14.7.18

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter_launcher_icons:
  image_path: "assets/appicon.jpg"
  android: true
  ios: true
  remove_alpha_ios: true
  android_12:
    image_path: "assets/appicon.jpg"

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/translations/
    - assets/images/