import 'package:flutter/material.dart';

const appName = "xHub";
const siteUrl = "https://api.xhub.biz/";
const apiUrl = "${siteUrl}api/v1/";
const loginUrl = "${apiUrl}login";
const registerUrl = "${apiUrl}registration";
const getCodeUrl = "${apiUrl}request_code";
const confirmUrl = "${apiUrl}verify_code";
const chatListUrl = "${apiUrl}conversations";
const shortcutsUrl = "${apiUrl}shortcuts";
const addShortcutUrl = "${apiUrl}shortcuts/add";
const filtersUrl = "$chatListUrl/get_filters";
const fileUploadUrl = "${siteUrl}files/upload";
const connectedUrl = "${apiUrl}connectors/";
const addConnectedUrl = "${connectedUrl}add";
const respondersUrl = "${apiUrl}autoresponders/";
const addResponderUrl = "${respondersUrl}add";
const userUrl = "${apiUrl}user/";
const myTeamUrl = "${userUrl}team";
const changePasswordUrl = "${userUrl}change_password";
const updateProfileUrl = "${userUrl}update";
const updateNotificationUrl = "${userUrl}update/notifications";
const primaryColor = Color(0xFF3498db);
const removeColor = Color(0xFFe74c3c);
const secondColor = Colors.black;
const chatMessageLimit = 20;
const chatListLimit = 20;